; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = espidf

monitor_filters = esp32_exception_decoder

build_flags =
    -D BLE_SENSE_ENABLED=1
    -DCONFIG_BT_BLE_ENABLED=1
    -DCONFIG_BT_BLUEDROID_ENABLED=1
    -DCONFIG_BT_BLE_50_FEATURES_SUPPORTED=0
    -DCONFIG_BT_BLE_42_FEATURES_SUPPORTED=1
    -DIDF_MAINTAINER=1
    -D CONFIG_FATFS_LFN_HEAP=1
    -D CONFIG_FATFS_MAX_LFN=255
    -DCONFIG_ESP_LCD_ENABLE_DEBUG_LOG=0

build_unflags =
    -Werror=all

lib_deps =
    git@github.com:SenseAI-Organization/data-logging-library.git#dev
    git@github.com:SenseAI-Organization/sensors-library.git#dev
    git@github.com:SenseAI-Organization/connectivity-library.git#feature/ble_code_style
    git@github.com:SenseAI-Organization/actuators-library.git#dev
